"""empty message

Revision ID: 43c2064ca6f8
Revises: fa146bdc4674
Create Date: 2025-05-07 14:54:36.227795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c2064ca6f8'
down_revision = 'fa146bdc4674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('email_approved')
        batch_op.drop_column('email_text')

    # ### end Alembic commands ###
