"""empty message

Revision ID: fa146bdc4674
Revises: a1f956962458
Create Date: 2025-05-06 16:13:33.046413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa146bdc4674'
down_revision = 'a1f956962458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_placements_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placements'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    # ### end Alembic commands ###
