"""empty message

Revision ID: 06481cd8ce6f
Revises: ea182bf803da
Create Date: 2025-05-12 14:14:35.440383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06481cd8ce6f'
down_revision = 'ea182bf803da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_suggestions_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    # ### end Alembic commands ###
