"""empty message

Revision ID: 0d00baf50b8c
Revises: f52eb8b95d6f
Create Date: 2026-03-25 21:19:17.457384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d00baf50b8c'
down_revision = 'f52eb8b95d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants_courses',
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['students.id'], name=op.f('fk_assistants_courses_assistant_id_students')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assistants_courses_course_id_courses')),
    sa.PrimaryKeyConstraint('assistant_id', 'course_id', name=op.f('pk_assistants_courses')),
    sa.UniqueConstraint('assistant_id', 'course_id', name=op.f('uq_assistants_courses_assistant_id'))
    )
    with op.batch_alter_table('students_courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_students_courses_student_id'), ['student_id', 'course_id'])

    with op.batch_alter_table('users_courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_courses_user_id'), ['user_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_courses_user_id'), type_='unique')

    with op.batch_alter_table('students_courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_students_courses_student_id'), type_='unique')

    op.drop_table('assistants_courses')
    # ### end Alembic commands ###
