"""empty message

Revision ID: 92a6eb2f8723
Revises: 0d00baf50b8c
Create Date: 2026-04-01 13:32:11.513500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a6eb2f8723'
down_revision = '0d00baf50b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assistant_reports_course_id_courses')),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_assistant_reports_instructor_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_assistant_reports_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_reports'))
    )
    with op.batch_alter_table('assistants_courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_assistants_courses_assistant_id'), ['assistant_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants_courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_assistants_courses_assistant_id'), type_='unique')

    op.drop_table('assistant_reports')
    # ### end Alembic commands ###
